[package]
name = "my_project"
version = "0.1.0"
edition = "2021"
lib = { path = "src/bin/lib.rs" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
